### ISSUE TITLE
Extension stopped working after update to 0.0.185

### ISSUE THREAD

**Issue by jens-duttke** [Gruntfuggly/todo-tree#380]
After your message in #362 I've updated the extension to Version 0.0.185, and now it doesn't work anymore.
In the debug console I get this output:
```
[2020-10-25 20:44:44.322] [exthost] [error] Activating extension Gruntfuggly.todo-tree failed due to an error:
[2020-10-25 20:44:44.322] [exthost] [error] Error: Cannot find module 'c:\Users\JDUTTKE\.vscode\extensions\gruntfuggly.todo-tree-0.0.185\src\extension.js'
Require stack:
- c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
	at Module._load (internal/modules/cjs/loader.js:737:27)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1057:776)
	at Function.i._load (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1027:486)
	at Function.n._load (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1023:767)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:34:963)
	at p._loadCommonJSModule (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1028:771)
	at p._doActivateExtension (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:742)
	at p._activateExtension (c:\Users\JDUTTKE\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:924:822)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 9)
	at async Promise.all (index 0)
```
Even uninstalling and installing again doesn't solve this problem.

**Comment by Gruntfuggly** [comment]
Sorry - I accidentally published a broken version. Please try version 0.0.186.
